import 'package:flutter/material.dart';

class LanguageManager {
  // Singleton instance
  static final LanguageManager instance = LanguageManager._internal();

  factory LanguageManager() {
    return instance;
  }

  LanguageManager._internal();

  // Current Locale
  final ValueNotifier<Locale> currentLocale = ValueNotifier(const Locale('en'));

  void changeLanguage(String code) {
    currentLocale.value = Locale(code);
  }

  // Translation Data
  final Map<String, Map<String, String>> _translations = {
    'en': {
      'app_title': 'Public Asset Monitoring',
      'app_subtitle': 'Smart Infrastructure Reporting',
      'dashboard': 'Dashboard',
      'total_reports': 'Total Reports',
      'pending': 'Pending',
      'in_progress': 'In Progress',
      'resolved': 'Resolved',
      'search_hint': 'Search requests, problems, locations...',
      'filter_dept': 'Filter by Department',
      'status': 'Status',
      'sort_by': 'Sort By',
      'latest': 'Latest',
      'oldest': 'Oldest',
      'urgent': 'Urgent',
      'reports': 'Reports',
      'no_reports': 'No reports available',
      'no_results': 'No results found',
      'departments': 'Departments',
      'admin_reports': 'All Reports (Admin)',
      'language': 'Language',
      'logout': 'Logout',
      'report_problem': 'Report Problem',
      'login_success': 'Login successful!',
      'logout_confirm': 'Are you sure you want to logout?',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      // Login
      'welcome_back': 'Welcome Back',
      'sign_in_continue': 'Sign in to continue',
      'email': 'Email',
      'password': 'Password',
      'login': 'Login',
      'dont_have_account': "Don't have an account? ",
      'register_here': 'Register here',
      'login_failed': 'Login failed',
      // Register
      'register': 'Register',
      'create_account': 'Create Account',
      'fill_details': 'Fill in your details to register',
      'full_name': 'Full Name',
      'age': 'Age',
      'phone_number': 'Phone Number',
      'gender': 'Gender',
      'address': 'Address',
      'confirm_password': 'Confirm Password',
      'already_have_account': 'Already have an account? ',
      'registration_successful': 'Registration successful!',
      // Report
      'report_a_problem': 'Report a Problem',
      'title': 'Title',
      'description': 'Description',
      'your_name': 'Your name',
      'your_email': 'Your email',
      'landmark': 'Landmark',
      'department': 'Department',
      'priority': 'Priority',
      'location': 'Location',
      'use_current': 'Use current',
      'photos': 'Photos',
      'video': 'Video',
      'submit_report': 'Submit Report',
      'submission_success':
          'Report submitted successfully! Authorities notified.',
      // Common & Errors
      'required': 'Required',
      'invalid_email': 'Invalid email',
      'password_too_short': 'Password too short',
      'passwords_mismatch': 'Passwords do not match',
      'select_gender': 'Please select a gender',
      'male': 'Male',
      'female': 'Female',
    },
    'ml': {
      'app_title': 'പൊതു ആസ്തി നിരീക്ഷണം',
      'app_subtitle': 'സ്മാർട്ട് ഇൻഫ്രാസ്ട്രക്ചർ റിപ്പോർട്ടിംഗ്',
      'dashboard': 'ഡാഷ്ബോർഡ്',
      'total_reports': 'ആകെ പരാതികൾ',
      'pending': 'തീർപ്പാക്കാത്തവ',
      'in_progress': 'പുരോഗതിയിലാണ്',
      'resolved': 'പരിഹരിച്ചവ',
      'search_hint': 'തിരയുക...',
      'filter_dept': 'വകുപ്പ് തിരിക്കുക',
      'status': 'അവസ്ഥ',
      'sort_by': 'ക്രമീകരിക്കുക',
      'latest': 'ഏറ്റവും പുതിയത്',
      'oldest': 'പഴയത്',
      'urgent': 'അടിയന്തരം',
      'reports': 'പരാതികൾ',
      'no_reports': 'പരാതികൾ ഒന്നുമില്ല',
      'no_results': 'ഫലങ്ങൾ ഒന്നുമില്ല',
      'departments': 'വകുപ്പുകൾ',
      'admin_reports': 'എല്ലാ റിപ്പോർട്ടുകളും (അഡ്മിൻ)',
      'language': 'ഭാഷ',
      'logout': 'പുറത്തുകടക്കുക',
      'report_problem': 'പരാതി നൽകുക',
      'login_success': 'ലോഗിൻ വിജയിച്ചു!',
      'logout_confirm': 'നിങ്ങൾക്ക് പുറത്തുകടക്കണോ?',
      'cancel': 'റദ്ദാക്കുക',
      'confirm': 'സ്ഥിരീകരിക്കുക',
      // Login
      'welcome_back': 'സ്വാഗതം',
      'sign_in_continue': 'തുടരാൻ ലോഗിൻ ചെയ്യുക',
      'email': 'ഇമെയിൽ',
      'password': 'പാസ്‌വേഡ്',
      'login': 'ലോഗിൻ',
      'dont_have_account': "അക്കൗണ്ട് ഇല്ലേ? ",
      'register_here': 'രജിസ്റ്റർ ചെയ്യുക',
      'login_failed': 'ലോഗിൻ പരാജയപ്പെട്ടു',
      // Register
      'register': 'രജിസ്റ്റർ',
      'create_account': 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
      'fill_details': 'വിശദാംശങ്ങൾ പൂരിപ്പിക്കുക',
      'full_name': 'പൂർണ്ണ നാമം',
      'age': 'വയസ്സ്',
      'phone_number': 'ഫോൺ നമ്പർ',
      'gender': 'ലിംഗഭേദം',
      'address': 'വിലാസം',
      'confirm_password': 'പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക',
      'already_have_account': 'അക്കൗണ്ട് ഉണ്ടോ? ',
      'registration_successful': 'രജിസ്ട്രേഷൻ വിജയിച്ചു!',
      // Report
      'report_a_problem': 'ഒരു പ്രശ്നം റിപ്പോർട്ട് ചെയ്യുക',
      'title': 'വിഷയം',
      'description': 'വിവരണം',
      'your_name': 'നിങ്ങളുടെ പേര്',
      'your_email': 'നിങ്ങളുടെ ഇമെയിൽ',
      'landmark': 'ലാൻഡ്മാർക്ക്',
      'department': 'വകുപ്പ്',
      'priority': 'മുൻഗണന',
      'location': 'സ്ഥലം',
      'use_current': 'നിലവിലെ സ്ഥലം',
      'photos': 'ഫോട്ടോകൾ',
      'video': 'വീഡിയോ',
      'submit_report': 'സമർപ്പിക്കുക',
      'submission_success': 'വിജയകരമായി സമർപ്പിച്ചു!',
      // Common & Errors
      'required': 'ആവശ്യമാണ്',
      'invalid_email': 'തറ്റായ ഇമെയിൽ',
      'password_too_short': 'പാസ്‌വേഡ് ചെറുതാണ്',
      'passwords_mismatch': 'പാസ്‌വേഡുകൾ പൊരുത്തപ്പെടുന്നില്ല',
      'select_gender': 'ലിംഗഭേദം തിരഞ്ഞെടുക്കുക',
      'male': 'പുരുഷൻ',
      'female': 'സ്ത്രീ',
    },
    'hi': {
      'app_title': 'सार्वजनिक संपत्ति निगरानी',
      'app_subtitle': 'स्मार्ट इंफ्रास्ट्रक्चर रिपोर्टिंग',
      'dashboard': 'डैशबोर्ड',
      'total_reports': 'कुल रिपोर्ट',
      'pending': 'लंबित',
      'in_progress': 'प्रगति में है',
      'resolved': 'सुलझाया हुआ',
      'search_hint': 'खोजें...',
      'filter_dept': 'विभाग द्वारा फ़िल्टर करें',
      'status': 'स्थिति',
      'sort_by': 'क्रमबद्ध करें',
      'latest': 'नवीनतम',
      'oldest': 'पुराना',
      'urgent': 'अत्यावश्यक',
      'reports': 'रिपोर्ट',
      'no_reports': 'कोई रिपोर्ट उपलब्ध नहीं है',
      'no_results': 'कोई परिणाम नहीं मिला',
      'departments': 'विभाग',
      'admin_reports': 'सभी रिपोर्ट (व्यवस्थापक)',
      'language': 'भाषा',
      'logout': 'लॉग आउट',
      'report_problem': 'समस्या की रिपोर्ट करें',
      'login_success': 'लॉगिन सफल!',
      'logout_confirm': 'क्या आप लॉग आउट करना चाहते हैं?',
      'cancel': 'रद्द करें',
      'confirm': 'पुष्टि करें',
      // Login
      'welcome_back': 'वापसी पर स्वागत है',
      'sign_in_continue': 'जारी रखने के लिए साइन इन करें',
      'email': 'ईमेल',
      'password': 'पासवर्ड',
      'login': 'लॉगिन',
      'dont_have_account': "खाता नहीं है? ",
      'register_here': 'यहाँ रजिस्टर करें',
      'login_failed': 'लॉगिन विफल',
      // Register
      'register': 'रजिस्टर',
      'create_account': 'खाता बनाएं',
      'fill_details': 'रजिस्टर करने के लिए विवरण भरें',
      'full_name': 'पूरा नाम',
      'age': 'आयु',
      'phone_number': 'फ़ोन नंबर',
      'gender': 'लिंग',
      'address': 'पता',
      'confirm_password': 'पासवर्ड की पुष्टि करें',
      'already_have_account': 'क्या आपके पास खाता है? ',
      'registration_successful': 'पंजीकरण सफल!',
      // Report
      'report_a_problem': 'समस्या की रिपोर्ट करें',
      'title': 'शीर्षक',
      'description': 'विवरण',
      'your_name': 'आपका नाम',
      'your_email': 'आपका ईमेल',
      'landmark': 'लैंडमार्क',
      'department': 'विभाग',
      'priority': 'प्राथमिकता',
      'location': 'स्थान',
      'use_current': 'वर्तमान स्थान',
      'photos': 'तस्वीरें',
      'video': 'वीडियो',
      'submit_report': 'रिपोर्ट जमा करें',
      'submission_success': 'सफलतापूर्वक जमा किया गया!',
      // Common & Errors
      'required': 'आवश्यक',
      'invalid_email': 'अमान्य ईमेल',
      'password_too_short': 'पासवर्ड बहुत छोटा है',
      'passwords_mismatch': 'पासवर्ड मेल नहीं खाते',
      'select_gender': 'कृपया लिंग चुनें',
      'male': 'पुरुष',
      'female': 'महिला',
    },
  };

  // Helper method to get string
  String t(String key) {
    final langCode = currentLocale.value.languageCode;
    return _translations[langCode]?[key] ?? _translations['en']?[key] ?? key;
  }
}
